# Usa la imagen base oficial de Node.js como imagen base
FROM node:16

# Crear un directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos de configuración y dependencias
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar todo el código fuente de tu aplicación
COPY . .

# Construir el proyecto de Nest.js (si tienes TypeScript)
RUN npm run build

# Exponer el puerto en el que Nest.js escucha (por defecto es el puerto 3000)
EXPOSE 3000

# Comando para iniciar la aplicación en modo producción
CMD ["npm", "run", "start:prod"]
