version: '3'

services:
  db: 
    image: postgres:14.15
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: opticaSystem 
    volumes:
      - ./postgres:/var/lib/postgresql/data

  #Gestor PGAdmin
  pgadmin:
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD:  ${PGADMIN_PASSWORD}
    ports:
      - "80:80"   
